cc_library(
  name = 'zk',
  srcs = [
    'ZkClient.cpp',
  ],
  deps = [
    '//boost:boost',
    '//folly:folly',
    '//thirdparty/gflags:gflags',
    '//thirdparty/glog:glog',
    '//toft/system/threading:threading',
    '//zookeeper:zookeeper',
  ]
)
