cc_binary(
  name = 'subscribe',
  srcs = [
    'ZkSubscribe.cpp',
  ],
  deps = [
    '//brood/zk:zk',
    '//jemalloc:jemalloc',
  ]
)

cc_binary(
  name = 'ephemeral',
  srcs = [
    'ZkEphemeral.cpp',
  ],
  deps = [
    '//brood/zk:zk',
    '//jemalloc:jemalloc',
  ]
)

cc_binary(
  name = 'ephemeral_sequence',
  srcs = [
    'ZkEphemeralSequence.cpp',
  ],
  deps = [
    '//brood/zk:zk',
    '//jemalloc:jemalloc',
  ]
)
